// This file is automatically generated.
// Please do not change this file!
interface CssExports {
	'animated-router-inner': string;
	'animated-router-outer': string;
	'fade-appear': string;
	'fade-appear-active': string;
	'fade-enter': string;
	'fade-enter-active': string;
	'fade-exit': string;
	'fade-exit-active': string;
}
export const cssExports: CssExports;
export default cssExports;
